disabled_rules: # rule identifiers to exclude from running
    - identifier_name
    - nesting
    - function_parameter_count
    - trailing_whitespace
    - empty_count
    - function_body_length
    - force_cast
    - type_body_length
    - no_fallthrough_only
    - file_length
    - unused_optional_binding
    - class_delegate_protocol
    - is_disjoint
    - todo
    - redundant_string_enum_value
    - block_based_kvo
#- type_name
opt_in_rules: # some rules are only opt-in
    - control_statement
    - empty_count
    - trailing_newline
    - colon
    - comma
included: # paths to include during linting. `--path` is ignored if present.
    - LocationBased Wikipedia
    - LocationBased WikipediaTests
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# force_cast: warning # implicitly. Give warning only for force casting

# force_try:
#    severity: warning # explicitly. Give warning only for force try

# type_body_length:
#    warning: 300
#error: 400

# or they can set both explicitly
# file_length:
#     warning: 750
#error: 800

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
    - 3
    - 4

line_length: 750

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
    min_length: 3 # only warning
    max_length: # warning and error
    warning: 47
    excluded: iPhone # excluded via string
reporter: "xcode"

cyclomatic_complexity:
    ignores_case_statements: true
    warning: 30
    error: 30

custom_rules:
    localizable_usage: # rule identifier
